### ISSUE TITLE
Failed on quick start

### ISSUE THREAD

**Issue by bromoapp** [nmarus/docker-mediadrop#1]
Hi,

I built your image inside docker under VMWare under Win10.
I follow your quickstart but everytime I try to access via browser, I got 502 Bad Gateway.
How to make this works?

P.S. I just learn to use docker. (just starting)

Thanks in advance
Bromo

**Comment by nmarus** [comment]
This should be fixed now. There was an issue with my forked repo at nmarus/mediadrop that referenced paths at static.mediadrop.net that are no longer valid or have been moved. I updated the fork at nmarus/mediadrop to the current version at mediadrop/mediadrop. Following the quickstart without modifying the docker-compose.yml now loads the server for me. 

Some further details...

After running the step `docker-compose up -d`, you can run `docker logs -f mediadrop-uwsgi` to monitor the setup of the uwsgi container.

Once you see...

```
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 847)
spawned uWSGI worker 1 (pid: 853, cores: 1)
spawned uWSGI worker 2 (pid: 854, cores: 1)
*** Stats server enabled on 127.0.0.1:9191 fd: 12 ***
```

... you can press ctrl-c to drop out of the log and the server should respond on the docker host on port 80.

Let me know if this fixes your problem.
